actions:
  - name: Install dependencies
    command: npm install --production
  - name: Build the application
    command: npm run build
  - name: List contents of out directory
    command: ls -la out/
  - name: Clean destination directory safely
    command: find $DOCUMENT_ROOT -mindepth 1 -not -path "$DOCUMENT_ROOT/.htaccess" -delete
  - name: Copy built files recursively
    command: rsync -av out/ $DOCUMENT_ROOT/
  - name: List contents of document root after copy
    command: ls -la $DOCUMENT_ROOT/
  - name: List _next directory specifically
    command: ls -la $DOCUMENT_ROOT/_next/
  - name: Set proper permissions
    command: chmod -R 755 $DOCUMENT_ROOT/ 